ChaiTea/ChaiTea.Web/Areas/Financials/Controllers/SuppliesController.cs
using ChaiTea.Web.Areas.Financials.Models;
using ChaiTea.Web.Common;
using ChaiTea.Web.Identity;
using System.Web.Mvc;

namespace ChaiTea.Web.Areas.Financials.Controllers
{
    [AuthorizedRoles(Roles = Roles.SuppliesViewers)]
    public class SuppliesController : MvcControllerBase
    {
        public SuppliesController()
        {
            ViewBag.Icon = "fa-quality";
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(string isBillable, string category, string subCategory, string isGreen)
        {
            return View(new FilterObjectVm
            {
                isBillable = isBillable,
                category = category,
                subCategory = subCategory,
                isGreen = isGreen
            });
        }

    }
}

ChaiTea/ChaiTea.Web/Areas/Financials/Views/Supplies/Details.cshtml
@using Newtonsoft.Json
@model ChaiTea.Web.Areas.Financials.Models.FilterObjectVm
@{
    ViewBag.Title = "Spend Reporting";
    ViewBag.HideTitleBar = true;
    var filterParams = new
    {
        category = @Model.category,
        isBillable = @Model.isBillable,
        subCategory = @Model.subCategory,
        isGreen = Model.isGreen
    };
}

<script type="text/ng-template" id="filter.html">
    <div class="margin-bottom-10">
        <select id="BillableType" name="Billable" class="selectpadding filter-option form-control" data-ng-model="vm.filterTypes.IsBillable">
            <option value="">- Select Billable Flag -</option>
            <option value="true">Yes</option>
            <option value="false">No</option>
        </select>
    </div>
    <div class="margin-bottom-10">
        <select id="GreenType" name="Green" class="selectpadding filter-option form-control width-attendance-details-align" data-ng-model="vm.filterTypes.IsGreen">
            <option value="">- Select Green Flag -</option>
            <option value="true">Yes</option>
            <option value="false">No</option>
        </select>
    </div>
    <div class="margin-bottom-10">
        <input class="form-control" type="text" data-ng-model="vm.filterTypes.Category" autofocus="autofocus" placeholder="Enter Category" />
    </div>

    <button data-ng-click="vm.cancel()" type="button" class="btn btn-default btn-sm col-xs-6">
        CLEAR
    </button>
    <button class="btn btn-warning btn-sm col-xs-6" data-ng-click="vm.getPurchaseOrdersReset()"
            data-ng-disabled="!vm.filterTypes.IsBillable && !vm.filterTypes.IsGreen && !vm.filterTypes.Category" type="button">
        FILTER
    </button>
    <div class="clearfix"></div>
</script>

<div class="container-fluid financials supplies-common supplies-details" data-ng-controller="SuppliesDetailsCtrl as vm" data-ng-init="vm.initialize(@JsonConvert.SerializeObject(filterParams))">
    <page-header title="Spend Reporting"
                 s3-icon-name="supplies.svg"
                 info-text="{{'View specific transactions and spends for a selected period of time, program and site.' | translate}}">
        <date-range-picker button-class="btn btn-primary btn-sm"></date-range-picker>
        <a hidden-customers href="http://b2b.sbmstore.com/system/login.php" class="btn btn-success btn-sm">
            <i class="fa fa-shop i-shop"></i> <span class="hidden-xs hidden-sm">{{'SHOP NOW' | translate }}</span>
        </a>

        <!--Mobile Dropdown-->
        <div uib-dropdown dropdown-append-to-body class="visible-xs-inline-block visible-sm-inline-block">
            <button class="btn btn-default" uib-dropdown-toggle>
                <span class="fa fa-more-options"></span>
            </button>
            <ul class="page-header-dropdown dropdown-menu dropdown-menu-right" uib-dropdown-menu>
                <li>
                    <button class="btn btn-default"
                            ng-click="$ctrl.popMobileModal('filter.html')">
                        <span class="fa fa-sliders"></span>
                        Filter By
                        <span class="fa fa-sort margin-left-20 visible-md-inline-block visible-lg-inline-block"></span>
                    </button>
                </li>
                <li>
                    <button ng-click="vm.export()">
                        <span class="fa fa-download"></span> {{'EXPORT' | translate }}
                    </button>
                </li>
            </ul>
        </div>
    </page-header>
    <utility-header>
        <tabs>
            <a href="@Url.Action("Index","Supplies")" class="btn btn-default text-capitalize">{{'CHARTS'|translate}}</a>
            <a href="@Url.Action("Details","Supplies")" class="btn btn-default active text-capitalize">{{'DETAILS'|translate}}</a>
        </tabs>
        <custom-buttons class="btn-group visible-md-inline-block visible-lg-inline-block">
            <button class="btn btn-default"
                    popover-placement="auto bottom"
                    popover-append-to-body="true"
                    popover-trigger="'outsideClick'"
                    uib-popover-template="'filter.html'">
                <span class="fa fa-sliders"></span>
                Filter By
                <span class="fa fa-sort margin-left-20 visible-md-inline-block visible-lg-inline-block"></span>
            </button>

            <button class="btn btn-default" ng-click="vm.export()">
                <span class="fa fa-download"></span> {{'EXPORT' | translate }}
            </button>
        </custom-buttons>
    </utility-header>
    <div class="row table-header">
        <div class="col-lg-1 col-md-1 hidden-sm hidden-xs">
            SBM #
        </div>
        <div class="col-lg-1 col-md-1 hidden-sm hidden-xs">
            MFG #
        </div>
        <div class="col-lg-2 col-md-2 hidden-sm hidden-xs">
            MFG CODE
        </div>
        <div class="col-lg-2 col-md-2 col-sm-5 col-xs-4 hidden-sm hidden-xs">
            DESCRIPTION 1
        </div>
        <div class="col-lg-2 col-md-2 col-sm-5 col-xs-4 hidden-md hidden-lg">
            ITEM
        </div>
        <div class="col-lg-2 col-md-2 hidden-sm hidden-xs">
            DESCRIPTION 2
        </div>
        <div class="col-lg-1 col-md-1 col-sm-3 col-xs-3">
            DATE
        </div>
        <div class="col-lg-1 col-md-1 hidden-sm hidden-xs">
            PROGRAM
        </div>
        <div class="col-lg-1 col-md-1 col-sm-2 col-xs-2 text-center">
            QTY
        </div>
        <div class="col-lg-1 col-md-1 col-sm-2 col-xs-3 text-right amount-align">
            AMOUNT
        </div>
    </div>
    <div class="text-center empty-wrap" ng-if="!vm.purchaseOrders.length">No data to display</div>
    <div class="row table-data" data-infinite-scroll="vm.getPurchaseOrderScroll()" data-infinite-scroll-distance="0" data-infinite-scroll-disabled="vm.isBusy">
        <div class="itemrow purchase-order-list" data-ng-repeat="purchaseOrder in vm.purchaseOrders">
            <div class="col-lg-1 col-md-1 hidden-sm hidden-xs">
                {{ purchaseOrder.SBMNumber }}
            </div>
            <div class="col-lg-1 col-md-1 hidden-sm hidden-xs word-align">
                {{purchaseOrder.ManufacturerNumber }}
            </div>
            <div class="col-lg-2 col-md-2 hidden-sm hidden-xs word-align">
                {{ purchaseOrder.ManufacturerName }}
            </div>
            <div class="col-lg-2 col-md-2 col-sm-5 col-xs-4 word-align">
                {{ purchaseOrder.DescriptionOne }}
            </div>
            <div class="col-lg-2 col-md-2 hidden-sm hidden-xs word-align">
                {{ purchaseOrder.DescriptionTwo }}
            </div>
            <div class="col-lg-1 col-md-1 col-sm-3 col-xs-3">
                {{ purchaseOrder.CommitmentDate | date: 'M/d/yy' }}
            </div>
            <div class="col-lg-1 col-md-1 hidden-sm hidden-xs hidden-md" ng-class="{'word-align': purchaseOrder.ProgramName.length > 15}">
                {{ purchaseOrder.ProgramName }}
            </div>
            <div class="col-md-1 hidden-sm hidden-xs hidden-lg word-align">
                {{ purchaseOrder.ProgramName }}
            </div>
            <div class="col-lg-1 col-md-1 col-sm-2 col-xs-2 text-center">
                {{ purchaseOrder.Quantity }}
            </div>
            <div class="col-lg-1 col-md-1 col-sm-2 col-xs-3 text-right amount-align">
                ${{ purchaseOrder.Amount | number : 2 }}
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>