ChaiTea/ChaiTea.Web/Areas/Personnel/Controllers/OwnershipController.cs
using ChaiTea.Web.Areas.Personnel.Models;
using ChaiTea.Web.Common;
using ChaiTea.Web.Identity;
using System.Web.Mvc;

namespace ChaiTea.Web.Areas.Personnel.Controllers
{
    [AuthorizedRoles]
    public class OwnershipController : MvcControllerBase
    {
        public OwnershipController()
        {
            ViewBag.Icon = "fa-personnel";
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }

        public ActionResult Entry(int? id = 0)
        {
            return View(new OwnershipVM
            {
                Id = id
            });
        }

        //
        // GET: /Personnel/Conduct/EntryView/
        public ActionResult EntryView(int? id = 0)
        {
            return View(new OwnershipVM
            {
                Id = id
            });
        }
    }
}

ChaiTea/ChaiTea.Web/Areas/Services/Controllers/ActionRequests/NoticedIssues/OwnershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using System.Web.Http.OData;

using ChaiTea.BusinessLogic.Services.ActionRequests.NoticedIssues;
using ChaiTea.BusinessLogic.ViewModels.ActionRequests.NoticedIssues;
using ChaiTea.BusinessLogic.ViewModels.Employment;
using ChaiTea.BusinessLogic.ViewModels.Utils;
using ChaiTea.Web.Identity;

namespace ChaiTea.Web.Areas.Services.Controllers.ActionRequests.NoticedIssues
{
    [AuthorizedRolesApi]
    [RoutePrefix(WebApiConfig.UrlPrefix + "/Ownership")]
    public class OwnershipController : BaseApiController
    {
        /// <summary>
        /// Get all active ReportIts
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [Route("")]
        [EnableQuery]
        public IQueryable<OwnershipVm> Get()
        {
            return new OwnershipService(UserCtx).Get();
        }

        /// <summary>
        /// Get ReportIt by Id. 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("{id:int}")]
        [ResponseType(typeof(OwnershipVm))]
        public IHttpActionResult Get(int id)
        {
            return Ok(new OwnershipService(UserCtx).Get(id));
        }

        /// <summary>
        /// Create a new ReportIt.
        /// </summary>
        /// <param name="vm"></param>
        /// <returns></returns>
        [HttpPost]
        [Route("")]
        [ResponseType(typeof(int))]
        public IHttpActionResult Post(OwnershipVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var newId = new OwnershipService(UserCtx).Create(vm);

            return Ok(new
                      {
                          OwnershipId = newId
                      });
        }

        /// <summary>
        /// Update an existing ReportIt.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="vm"></param>
        /// <returns></returns>
        [HttpPut]
        [Route("{id:int}")]
        [ResponseType(typeof(void))]
        public IHttpActionResult Put(int id, OwnershipVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            vm.OwnershipId = id;

            var success = new OwnershipService(UserCtx).Update(vm);

            if (success)
            {
                return Ok();
            }

            return ResponseMessage(new HttpResponseMessage(HttpStatusCode.NotModified));
        }

        [HttpGet]
        [Route("EmployeesOwnershipsCount")]
        [ResponseType(typeof(List<EmployeeMetricVm>))]
        [EnableQuery] // TODO: Yes, we are using OData here despite the return type being List in order for front-end to sort/skip/top
        public IHttpActionResult GetEmployeesOwnershipsCount(DateTime startDate, DateTime endDate)
        {
            return Ok(new OwnershipService(UserCtx).GetOwnershipsCountByEmployees(startDate, endDate));
        }

        [HttpGet]
        [Route("SiteCounts")]
        [ResponseType(typeof(List<OwnershipSiteCountVm>))]
        [EnableQuery] // TODO: Yes, we are using OData here despite the return type being List in order for front-end to sort/skip/top
        public IHttpActionResult GetOwnershipCounts(DateTime startDate, DateTime endDate)
        {
            return Ok(new OwnershipService(UserCtx).GetOwnershipsCountBySites(startDate, endDate));
        }

        /// <summary>
        /// Get the ReportIts (Ownership) counts per month.
        /// </summary>
        /// <param name="startDate"></param>
        /// <param name="endDate"></param>
        /// <returns></returns>
        [HttpGet]
        [ResponseType(typeof(IEnumerable<MapCountsBySiteVm>))]
        [Route("OwnershipCountBySiteByMonth")]
        public IHttpActionResult GetOwnershipCountBySiteByMonth(DateTime startDate, DateTime endDate)
        {
            return Ok(new OwnershipService(UserCtx).GetOwnershipCountBySiteByMonth(startDate, endDate));
        }

        /// <summary>
        /// Delete request (ownership).
        /// </summary>
        /// <param name="id"></param>
        /// <returns>bool</returns>
        [HttpDelete]
        [Route("{id:int}")]
        [ResponseType(typeof(bool))]
        [AuthorizedRolesApi(Roles = Roles.CrazyProgrammers)]
        public async Task<IHttpActionResult> Delete(int id)
        {
            return Ok(await new OwnershipService(UserCtx).Delete(id));
        }
    }
}

ChaiTea/ChaiTea.Web/Areas/Services/Controllers/ActionRequests/NoticedIssues/v1_1/OwnershipController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;

using ChaiTea.BusinessLogic.AppUtils.DataFilters;
using ChaiTea.BusinessLogic.Reporting.Training.Models;
using ChaiTea.BusinessLogic.Services.ActionRequests.NoticedIssues.v1_1;
using ChaiTea.BusinessLogic.ViewModels.ActionRequests.NoticedIssues;
using ChaiTea.BusinessLogic.ViewModels.Employment;
using ChaiTea.BusinessLogic.ViewModels.Utils;
using ChaiTea.BusinessLogic.ViewModels.Utils.Pagination;
using ChaiTea.Web.Identity;

namespace ChaiTea.Web.Areas.Services.Controllers.ActionRequests.NoticedIssues.v1_1
{
    [AuthorizedRolesApi]
    [RoutePrefix(WebApiConfig.UrlPrefix_v1_1 + "/Ownership")]
    public class Ownership_v11Controller : BaseApiController
    {
        /// <summary>
        /// Get Ownership (ReportIt) records to which the logged in user has permissions, matching the supplied
        /// search criteria.
        /// </summary>
        /// <param name="startDate">Start date</param>
        /// <param name="endDate">End date</param>
        /// <param name="skip">Skip this many records</param>
        /// <param name="take">Return (at most) this many records</param>
        /// <param name="filterOnStatus">Filter on the status of the ReportIt? (default: false)</param>
        /// <param name="status">If filterOnStatus is true, the value to filter on should be supplied.</param>
        /// <returns>An enumerable list of <see cref="OwnershipVm"/></returns>
        [HttpGet]
        [Route("")]
        [ResponseType(typeof(IEnumerable<OwnershipVm>))]
        public async Task<IHttpActionResult> Get(DateTime? startDate = default, DateTime? endDate = default, int? skip = default, int? take = default, bool filterOnStatus = default, bool? status = default)
        {
            var dateFilter = new DateTimeOptionalRange(startDate, endDate);
            var pagingFilter = PagingFilter.TryValidate(skip, take);

            using (var svc = new OwnershipService(UserCtx))
            {
                return Ok(await svc.GetByTagsAsync(pagingFilter, dateFilter, filterOnStatus, status, null));
            }
        }

        /// <summary>
        /// Get Ownership (ReportIt) records to which the logged in user has permissions, matching the supplied
        /// search criteria.
        /// </summary>
        /// <param name="tags">The list of building tags to match against - list cannot be empty</param>
        /// <param name="startDate">Start date</param>
        /// <param name="endDate">End date</param>
        /// <param name="skip">Skip this many records</param>
        /// <param name="take">Return (at most) this many records</param>
        /// <param name="filterOnStatus">Filter on the status of the ReportIt? (default: false)</param>
        /// <param name="status">If filterOnStatus is true, the value to filter on should be supplied.</param>
        /// <returns>An enumerable list of <see cref="OwnershipVm"/></returns>
        [HttpPost]
        [Route("ByTags")]
        [ResponseType(typeof(IEnumerable<OwnershipVm>))]
        public async Task<IHttpActionResult> GetByTags([FromBody] List<string> tags, DateTime? startDate = null, DateTime? endDate = null, int? skip = null, int? take = null, bool filterOnStatus = false, bool? status = default)
        {
            if (tags == null ||
                tags.Count < 1)
            {
                throw new ArgumentException("No tags passed.", nameof(tags));
            }

            var dateFilter = new DateTimeOptionalRange(startDate, endDate);
            var pagingFilter = PagingFilter.TryValidate(skip, take);

            using (var svc = new OwnershipService(UserCtx))
            {
                return Ok(await svc.GetByTagsAsync(pagingFilter, dateFilter, filterOnStatus, status, tags));
            }
        }

        /// <summary>
        /// Returns a summary of Ownership (ReportIt) records grouped by Site ID, based on the tag list provided.
        /// </summary>
        /// <param name="tags">ServiceAreaTags to use for searching ReportIts - cannot be empty.</param>
        /// <param name="startDate">Beginning of the range.</param>
        /// <param name="endDate">End of the range.</param>
        /// <param name="take">Number of rows to take.</param>
        /// <param name="skip">Number of pages to skip.</param>
        /// <returns>An <see cref="OwnershipSummary">OwnershipSummary</see> object with the summary data.</returns>
        [HttpPost]
        [Route("SiteSummariesByTags")]
        [ResponseType(typeof(PaginatedData<OwnershipSummary>))]
        public async Task<IHttpActionResult> GetSiteSummariesByTags([FromBody] List<string> tags, DateTime startDate, DateTime endDate, int? take = null, int? skip = null)
        {
            if (tags == null ||
                tags.Count < 1)
            {
                throw new ArgumentException("No tags passed.", nameof(tags));
            }

            var dateFilter = new DateTimeRequiredRange(startDate, endDate);
            var pagingFilter = PagingFilter.TryValidate(skip, take);

            using (var svc = new OwnershipService(UserCtx))
            {
                return Ok(await svc.GetSiteSummariesByTagsAsync(tags, pagingFilter, dateFilter));
            }
        }

        /// <summary>
        /// Returns a summary of Ownership (ReportIt) by Site ID
        /// </summary>
        /// <param name="id">Site ID</param>
        /// <param name="startDate">Beginning date of the Ownership range</param>
        /// <param name="endDate">End date of the Complaint range</param>
        /// <returns></returns>
        [HttpGet]
        [Route("SiteSummary")]
        [ResponseType(typeof(OwnershipSiteSummary))]
        public async Task<IHttpActionResult> GetSiteSummary(int id, DateTime startDate, DateTime endDate)
        {
            var dateFilter = DateTimeRangeFilter.TryValidateRequired(startDate, endDate);
            
            using (var svc = new OwnershipService(UserCtx))
            {
                return Ok(await svc.GetSiteSummary(id, dateFilter));
            }
        }
        
        /// <summary>
        /// Returns a summary of the Ownership (ReportIt) records for all sites.
        /// </summary>
        /// <param name="tags">ServiceAreaTags to use for searching compliments - cannot be empty.</param>
        /// <param name="startDate">Beginning of the FeedbackDate range.</param>
        /// <param name="endDate">End of the FeedbackDate range.</param>
        /// <returns>An <see cref="OwnershipSummary">OwnershipSummary</see> object with the summary data.</returns>
        [HttpPost]
        [Route("AllSiteSummariesByTags")]
        [ResponseType(typeof(OwnershipSummary))]
        public async Task<IHttpActionResult> GetAllSiteSummariesByTags([FromBody] List<string> tags, DateTime startDate, DateTime endDate)
        {
            if (tags == null ||
                tags.Count < 1)
            {
                throw new ArgumentException("No tags passed.", nameof(tags));
            }

            var dateFilter = new DateTimeRequiredRange(startDate, endDate);

            using (var svc = new OwnershipService(UserCtx))
            {
                return Ok(await svc.GetAllSiteSummariesByTagsAsync(tags, dateFilter));
            }
        }

        /// <summary>
        /// Get a single Ownership (ReportIt) by Id.
        /// </summary>
        /// <returns>A <see cref="OwnershipVm">ReportIt</see> with the matching Id (if found)</returns>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        [HttpGet]
        [Route("{id:int}")]
        [ResponseType(typeof(OwnershipVm))]
        public IHttpActionResult Get(int id)
        {
            using (var svc = new OwnershipService(UserCtx))
            {
                return Ok(svc.Get(id));
            }
        }

        /// <summary>
        /// Create a new Ownership (ReportIt).
        /// </summary>
        /// <returns>A JSON object with the Id of the newly created ReportIt's Id</returns>
        [HttpPost]
        [Route("")]
        [ResponseType(typeof(object))]
        public IHttpActionResult Post(OwnershipVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            using (var svc = new OwnershipService(UserCtx))
            {
                var newId = svc.Create(vm);

                return Ok(new
                          {
                              OwnershipId = newId
                          });
            }
        }

        /// <summary>
        /// Update an existing Ownership (ReportIt) record (by Id)
        /// </summary>
        /// <param name="id">The Id of the ReportIt to be updated.</param>
        /// <param name="vm">The <see cref="OwnershipVm">ReportIt</see> data</param>
        /// <returns>A JSON object indicating the success (or failure) of the update operation</returns>
        /// <exception cref="ArgumentOutOfRangeException"></exception>
        [HttpPut]
        [Route("{id:int}")]
        [ResponseType(typeof(bool))]
        public IHttpActionResult Put(int id, OwnershipVm vm)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            vm.OwnershipId = id;

            using (var svc = new OwnershipService(UserCtx))
            {
                if (svc.Update(vm))
                {
                    return Ok();
                }

                return ResponseMessage(new HttpResponseMessage(HttpStatusCode.NotModified));
            }
        }

        /// <summary>
        /// Get the count of ReportIts on a per-site basis, per employee.
        /// </summary>
        /// <param name="startDate">Start date</param>
        /// <param name="endDate">End date</param>

ChaiTea/ChaiTea.Web/Areas/Personnel/Views/Ownership/Details.cshtml
@{
    ViewBag.Title = "Report It";
    ViewBag.HideTitleBar = true;
}

@section scripts{
<script type="text/ng-template" id="manageCustomerRepresentatives.tmpl.html">
    <div class="btn-group btn-block">
        <button class="col-sm-12 col-md-12 btn btn-default dropdown-toggle" ng-click="toggleSelect()" ng-disabled="disabled" ng-class="{'error': !valid()}" style="width: 100%;">
            <div class="pull-left">{{header}}</div> <div class="pull-right"><span class="caret"></span></div>
        </button>
        <a class="closer btn btn-xs btn-default" ng-click="toggleSelect()">close <span class="fa fa-close"></span></a>
        <ul class="dropdown-menu col-sm-12 col-md-12" style="width: 100%; max-height: 300px; overflow-y: scroll; overflow-x: hidden;">
            <li style="width: 100%;">
                <input class="form-control" type="text" ng-model="searchText.label" placeholder="Filter" />
            </li>
            <li style="width: 100%;">
                <button class="btn-link btn-small pull-right" ng-click="uncheckAll()"><i class="glyphicon glyphicon-remove"></i> <span translate>Uncheck all</span></button>
                <button class="btn-link btn-small pull-right" ng-click="checkAll()"><i class="glyphicon glyphicon-ok"></i> <span translate>Check all</span></button>
            </li>
            <li>
                <a href="javascript:void(0);" data-ng-click="vm.addNewCustomerRepresentative($event)">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span translate>Add New</span>
                </a>
            </li>
            <li ng-repeat="i in items | filter:searchText" style="width: 275px;">
                <a ng-click="select(i);" style="line-height: 25px; display: block; cursor: pointer;">
                    <i ng-class="{'glyphicon glyphicon-ok': i.checked, '': !i.checked}"></i> {{i.label}}
                </a>
            </li>

        </ul>
    </div>
</script>
}

<div class="container-fluid personnel attendance-view ownership" data-ng-controller="Personnel.OwnershipDetailsCtrl as vm" data-ng-init="vm.initialize()">
    <page-header title="Report It"
                 s3-icon-name="reportit.svg"
                 info-text="{{'View a list of your reports here, and enter new report during your shift.' | translate}}">
        <date-range-picker button-class="btn btn-primary btn-sm"></date-range-picker>
        <a hidden-customers href="@Url.Content("~/Personnel/Ownership/Entry")" class="btn btn-success btn-sm">
            + <span class="hidden-xs hidden-sm">{{'NEW REPORT' | translate }}</span>
        </a>
    </page-header>
    <utility-header>
        <tabs>
            <a href="@Url.Action("Index", "Ownership")" class="btn btn-default text-capitalize">Charts</a>
            <a href="@Url.Action("Details", "Ownership")" class="btn btn-default text-capitalize active">Details</a>
        </tabs>
        <custom-buttons class="btn-group visible-md visible-lg">
            <button class="btn btn-default" ng-click="vm.export()">
                <span class="fa fa-download"></span> {{'EXPORT' | translate }}
            </button>
        </custom-buttons>
    </utility-header>

    <div class="row">
        <div class="panel panel-default no-border">
            <div class="center-cards">
                <tab-filter-header class="padding-horizontal-5 padding-top-20" tab-items="vm.tabFilterItems"></tab-filter-header>
                <utility-nav-filter-tags></utility-nav-filter-tags>
            </div>

            <div class="text-center empty-wrap" ng-if="!vm.ownership.length" translate>No data to display</div>
            <div class="card-view-style center-cards">
                <div data-infinite-scroll="vm.getOwnerships()" data-infinite-scroll-distance="0" data-infinite-scroll-disabled="vm.isBusy">
                    <card class="col-md-4 col-sm-6 col-xs-12 card-size card-align" ng-transclude
                          ng-repeat="details in vm.ownership">
                        <card-header ng-transclude>
                            <quality-card-header module="vm.module" header-text="vm.headerText" item-id="details.OwnershipId" format-date="false" custom-format-date="true" view-link-fn="vm.ShowEntryViewModal(id)"
                                                 header-date="details.CreateDate">
                            </quality-card-header>
                        </card-header>
                        <card-body ng-transclude>
                            <div class="card-body-content">
                                <div>
                                    <div class="pull-left">
                                        <img class="employee-img move" ng-src="{{details._createByProfilePicture}}" err-src="{{vm.sitesettings.defaultProfileImage}}" />
                                    </div>
                                    <div class="pull-left associate-section">
                                        <span class="name truncate">{{details.EmployeeName}}</span>
                                        <p class="name-lbl text-muted">
                                            {{'ASSOCIATE' | translate}}
                                            <span data-ng-if="details.IsCritical != null" class="type padding-left-5">
                                                {{details.IsCritical == 0 ? 'NON_CRITICAL' : 'Critical' | translate}}
                                            </span>
                                            <span data-ng-if="details.RejectionTypeName" class="type padding-left-5">
                                                {{details.RejectionTypeName}}
                                            </span>
                                        </p>

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                                <div class="clearfix"></div>
                                <div ng-if="details.Description" class="margin-top-25 truncate">
                                    {{details.Description}}
                                </div>
                                <div class="site padding-top-5">
                                    <p class="pull-left building-name" ng-class="{'building truncate' : (details.BuildingName.length + details.FloorName.length) > 15}">
                                    {{details.BuildingName}}, {{details.FloorName}}</p>
                                    <div class="pull-left padding-left-15" ng-class="{'site-client truncate' : (vm.clientName + (vm.siteName ? vm.siteName.length : 0)) > 20}">
                                        <i class="fa fa-location margin-right-5"></i>
                                        <span>{{vm.clientName}}
                                            <span ng-if="vm.siteName">, {{vm.siteName}}</span>
                                        </span>
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                        </card-body>
                        <card-footer ng-transclude>
                            <div class="card-footer-content">
                                <div class="pull-left" ng-if="details.ReportTypeName" ng-class="{'fit-height': details.IsCritical != 1}">
                                    <span class="relatedTo margin-right-10 truncate" >{{details.ReportTypeName}}</span>
                                </div>
                                <div class="pull-left fit-no-type" ng-if="!details.ReportTypeName && details.IsCritical != 1">
                                </div>
                                <div class="pull-left truncate customer-rep" ng-if="details.IsCritical == 1">
                                    <span class="text-muted text-capitalize">{{'CUSTOMER_REP' | translate}}: </span>
                                    <span class="text-muted text-capitalize">{{details.CustomerRepresentatives[0].Name}}</span>
                                    <span class="text-muted" ng-if="details.CustomerRepresentatives.length > 1">, +{{details.CustomerRepresentatives.length-1}}</span>
                                </div>
                                <div class="pull-right types" ng-if="details.Status == null && vm.isManager">
                                    <a class="text-warning click-style"  data-ng-click="vm.accept(details,$event)">
                                        {{'ACCEPT' | translate}}
                                    </a>
                                    <a class="text-warning padding-left-15 click-style"  data-ng-click="vm.reject(details,$event)">
                                        {{'REJECT' | translate}}
                                    </a>
                                </div>
                            </div>
                        </card-footer>
                        <div class="clearfix"></div>
                    </card>
                    <div class="clearfix"></div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>

    </div>
</div>