ChaiTea/ChaiTea.Web/Areas/Admin/Controllers/KnowledgeCenterController.cs
using ChaiTea.Web.Common;
using ChaiTea.Web.Identity;
using System.Web.Mvc;

namespace ChaiTea.Web.Areas.Admin.Controllers
{
    public class KnowledgeCenterController : MvcControllerBase
    {
        [AuthorizedRoles(Roles = Roles.Managers)]
        public ActionResult CourseTypes()
        {
            return View();
        }

        [AuthorizedRoles(Roles = Roles.TrainingAdmins)]
        public RedirectResult CourseAdmin()
        {
            return Redirect("../../Training/Course/Index");
        }
    }
}

ChaiTea/ChaiTea.Web/Areas/Services/Controllers/Courses/CourseController.cs
using ChaiTea.BusinessLogic.AppUtils.Interfaces;
using ChaiTea.BusinessLogic.Services.Courses;
using ChaiTea.BusinessLogic.ViewModels.Courses;
using ChaiTea.Web.Identity;
using System;
using System.Web.Http;

namespace ChaiTea.Web.Areas.Services.Controllers.Courses
{
    [AuthorizedRolesApi]
    [RoutePrefix(WebApiConfig.UrlPrefix + "/Course")]
    public class CourseController : BaseCrudApiController<CourseVm>
    {
        protected override Func<CourseVm, int> GetIdentifier
        {
            get { return vm => vm.CourseId; }
        }

        protected override Action<CourseVm, int> SetIdentifier
        {
            get { return (vm, id) => vm.CourseId = id; }
        }

        protected override ICrudService<CourseVm> CreateService
        {
            get { return new CourseService(UserCtx); }
        }
    }
}

ChaiTea/ChaiTea.Web/Areas/Training/Controllers/CourseController.cs
using ChaiTea.Web.Areas.Training.Models;
using ChaiTea.Web.Common;
using ChaiTea.Web.Identity;
using System.Web.Mvc;

namespace ChaiTea.Web.Areas.Training.Controllers
{
    [AuthorizedRoles]
    public class CourseController : MvcControllerBase
    {
        public CourseController()
        {
            ViewBag.Icon = "icon-books2";
        }

        // GET: Training/Course
        [AuthorizedRoles(Roles = Roles.TrainingAdmins)]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Training/Course/EntryView/{id}
        [AuthorizedRoles(Roles = Roles.TrainingAdmins)]
        public ActionResult EntryView(int? id = 0)
        {
            return View("EntryView", new TrainingVm
            {
                Id = id
            });
        }

        // GET: Training/Course/Entry
        [AuthorizedRoles(Roles = Roles.TrainingAdmins)]
        public ActionResult Entry(int? id = 0)
        {
            return View("Entry", new TrainingVm
            {
                Id = id
            });
        }



        // GET: Training/Course/Assign
        [AuthorizedRoles(Roles = Roles.TrainingAdmins)]
        public ActionResult Assign()
        {
            return View();
        }

        // GET: Training/Course/Assign
        [AuthorizedRoles(Roles = Roles.TrainingAdmins)]
        public ActionResult Unassign()
        {
            return View();
        }

        [AuthorizedRoles(Roles = Roles.TrainingAdmins)]
        public RedirectResult Settings()
        {
            return Redirect("../../Admin/KnowledgeCenter/CourseTypes");
        }
    }
}

ChaiTea/ChaiTea.Web/Areas/Training/Controllers/KnowledgeCenterController.cs
using ChaiTea.Web.Common;
using ChaiTea.Web.Identity;
using System.Web.Mvc;

namespace ChaiTea.Web.Areas.Training.Controllers
{
    [AuthorizedRoles]
    public class KnowledgeCenterController : MvcControllerBase
    {
        public KnowledgeCenterController()
        {
            ViewBag.Icon = null;
        }

        // GET: Training/KnowledgeCenter
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EntryView(int id, string pageTitle = "")
        {
            return View(new KnowledgeCenterVm{ Id = id, PageTitle = pageTitle });
        }

        public ActionResult TakeCourse(int id, int employeeId = 0, string pageTitle = "",int courseTypeId = 0)
        {
            return View(new KnowledgeCenterVm { Id = id, EmployeeId = employeeId, PageTitle = pageTitle,CourseTypeId = courseTypeId });
        }

        public ActionResult TakeQuiz(int id, int courseAttachmentId = 0)
        {
            return View(new KnowledgeCenterVm { EmployeeCourseId = id, CourseAttatchmentId = courseAttachmentId});
        }
    }

    public class KnowledgeCenterVm
    {
        public int Id { get; set; }
        public string PageTitle { get; set; }
        public int EmployeeId { get; set; }

        public int CourseId { get; set; }

        public int EmployeeCourseId { get;set; }

        public int CourseAttatchmentId { get;set; }
        public int CourseTypeId { get; set; }
    }
}

ChaiTea/ChaiTea.Web/Areas/Admin/Views/KnowledgeCenter/CourseTypes.cshtml
@using Newtonsoft.Json
@{
    ViewBag.Title = "Course Types";
}


<div class="container-fluid" data-ng-controller="Admin.CourseTypesCtrl as vm" data-ng-init="vm.initialize()">
    <div class="row">        
        <div class="col-md-8 margin-bottom-20">
            <a class="btn btn-default btn-md unassign-btn" href="@Url.Action("CourseAdmin", "KnowledgeCenter")">
                    <i class="fa fa-back"></i> <span> Return to Course Admin</span>
            </a>
            <button class="btn btn-success" ng-click="vm.createNew()">
                <span class="fa fa-plus"></span> Create New
            </button>
        </div>
        <div class="col-md-6 col-xs-12 col-sm-6 pull-left">

            <p>Click in the column to edit Course Types.  To add a new Course Type, click the Create New button and enter a Course Type name first before selecting an Icon.</p>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="gridStyle grid" ui-grid="gridOptions" ui-grid-edit ui-grid-cellNav ui-grid-pinning id="uiSelect" external-scopes="CourseTypesCtrl"></div>
        </div>
    </div>    
</div>